name: 'Dev Release'

on:
  push:
    tags: 'v[0-9]+.[0-9]+.[0-9]+-digabi.[0-9]+'

concurrency:
  group: ${{ github.ref_name }}

jobs:
  dev-release:
    name: Release to private ECR
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.UTILITY_ACCOUNT_ID }}:role/KetcherGithubActionsAccessRole
          aws-region: eu-north-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - name: Set VERSION variable
        run: echo "APP_VERSION=$(git describe --tags --abbrev=0 || echo 'version-missing')" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/ketcher:${{ github.ref_name }}
          provenance: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: APP_VERSION=${{ env.APP_VERSION }}